baseurl = "http://blog.markfrancis.io"
title = "Mark James Francis"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

enableEmoji = true

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Mark James Francis"
  info = "Senior DevOps Engineer"
  description = "Marks personal website"
  keywords = "blog,developer, devops,cloud,personal"
  avatarurl = "/images/avatar.jpeg"
  # gravatar = "john.doe@example.com"

  # For the footer copywrite
  since = 2016
  #dateFormat = "January 2, 2006"

  colorScheme = "auto"

  # Series see also post count
  maxSeeAlsoItems = 5

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/francis-io"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "post/"
[[menu.main]]
  name = "CV"
  weight = 2
  url = "https://docs.google.com/document/d/1gUNrRtR7Pvk0oRyUXoC64oA3aPXXEYnM/edit?usp=sharing&ouid=107637890190679795874&rtpof=true&sd=true"
