version: '3'

services:
  hugo:
    env_file: .env
    build:
      context: .
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        HUGO_VERSION: ${HUGO_VERSION}
    volumes:
      - .:/srv/hugo
    ports:
      - 8080:8080
